module.exports = {
    Admin: require('./Admin'),
    Scholar: require('./Scholar'),
    Application: require('./Application'),
    Scholarship: require('./Scholarship'),
    ScholarshipApplication: require('./ScholarshipApplication'),
    ContactMessage: require('./ContactMessage'),
    AcademicCredential: require('./AcademicCredential'),
    TravelDocument: require('./TravelDocument'),
    VisaWorkflow: require('./VisaWorkflow'),
    Session: require('./Session'),
    VerificationToken: require('./VerificationToken'),
    AuditLog: require('./AuditLog'),
    Notification: require('./Notification'),
};
